document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: simon-encrypted-demo
  version: 0.0.1
  metadata:
    scheduleWorkflowName: simon-encrypted-demo
    scheduleId: simon-encrypted-demo
schedule:
  every:
    hours: 2
do:
  - wait:
      wait:
        seconds: 30
  - set:
      set:
        email: simon.emms@temporal.io
        cardHolder: Simon Emms
        cardNumber: 4111 1111 1111 1111
        expiry: 12/29
        cvv: 123
        message: |-
          This is a message encrypted with AES and decoded in the browser
          by the Temporal Codec Server. Temporal never sees this data and it's
          only visible within your network.
